version: '3.8'
services:
  app:
    build: .
    restart: always
    ports:
      - "8090:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ecommercedb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  mysql:
    image: mysql:8.1.0
    environment:
     - MYSQL_DATABASE=ecommercedb
     - MYSQL_ROOT_PASSWORD=rootpassword
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=rootpassword --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - mysqldata:/var/lib/mysql

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
volumes:
  mysqldata:
