spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommercedb
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2000

  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 900s  # Same time as JWT's lifespan

springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
  override-with-generic-response: false

logging:
  level:
    com.jorge.ecommerce: debug